# Generated by Django 4.0.4 on 2022-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typing_indicator',
            field=models.BooleanField(default=True),
        ),
    ]
