# Generated by Django 4.0.4 on 2022-05-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_typing_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_indicator',
            field=models.BooleanField(default=True),
        ),
    ]
