# Generated by Django 4.0.4 on 2022-05-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_online_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
