# Generated by Django 4.0.4 on 2022-05-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_seversettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeverSettings',
            new_name='ServerSettings',
        ),
    ]
