# Generated by Django 4.0.4 on 2022-05-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_seversettings_serversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='name',
            field=models.CharField(default='session', max_length=20, unique=True),
        ),
    ]
