# Generated by Django 4.0.4 on 2022-05-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_serversettings_description_serversettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='secret',
            field=models.CharField(default='291641fc8698423d8a0c7b7cb01a2a47', max_length=100, unique=True),
        ),
    ]
