# Generated by Django 4.0.4 on 2022-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_serversettings_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversettings',
            name='secret',
            field=models.CharField(default='8b67e83245034b6380beca938a9cc470', max_length=100, unique=True),
        ),
    ]
