# Generated by Django 4.0.4 on 2022-05-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectMessage',
            new_name='PrivateChat',
        ),
    ]
