# Generated by Django 4.0.4 on 2022-05-11 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessage', '0002_rename_directmessage_privatechat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateChat',
            new_name='DirectChat',
        ),
        migrations.RenameModel(
            old_name='PrivateMessage',
            new_name='DirectMessage',
        ),
    ]
