# Generated by Django 4.0.4 on 2022-05-11 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directmessage', '0003_rename_privatechat_directchat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
