# Generated by Django 4.0.4 on 2022-05-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0004_directchat_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directmessage',
            old_name='message',
            new_name='directchat',
        ),
    ]
