# Generated by Django 4.0.4 on 2022-05-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0005_rename_message_directmessage_directchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directchat',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
