# Generated by Django 4.0.4 on 2022-04-25 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='net',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
