# Generated by Django 4.0.4 on 2022-04-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nets', '0002_alter_message_date_sent_alter_net_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='net',
            name='description',
        ),
    ]
